{{- if .Values.minio.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devproof-minio-data
spec:
  accessModes: [ReadWriteOnce]
  {{- with .Values.minio.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.minio.persistence.size }}
{{- end }}
